### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by WDragon101** [DBOSlab/expowo#3]
I tried example script in Appendix S1 of Zuanny et al.—Applications in Plant Sciences 2024—Data Supplement S1—Page 2 of 6
DOI 10.1002/aps3.11609.

`all_angio <- expowo::powoSpecies(family = angio$family,
 hybrid = FALSE,
 synonyms = TRUE,
 country = NULL,
 verbose = TRUE,
 rerun = FALSE,
 save = TRUE,
 dir = "results_powoSpecies",
 filename = "all_angio_species")`

Error happened:

Error in file(con, "r") : 
  cannot open the connection to 'http://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:30000155-2'
此外: Warning message:
In file(con, "r") :
  URL 'https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:30000155-2': status was 'SSL peer certificate or SSH remote key was not OK'

**Comment by gaofeng-cas** [comment]
i have the same problem， can you share the way to solve？ thanks a lot
